services:
  python:
    image: python:latest
    #image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    volumes:
      - ./:/home/vscode/GoodreadsSimilars/
    depends_on:
      - mongo
    networks:
      - app-tier
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - app-tier
    ports:
      - 27017:27017

networks:
  app-tier:
    driver: bridge
